[greeter]
background=/usr/share/backgrounds/shadow.png
theme-name=Breeze
icon-theme-name=breeze
font-name=DejaVu Sans 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
xft-rgba=rgb
indicators=~host;~spacer;~clock;~power
