[LightDM]
greeter-session=lightdm-gtk-greeter
greeter-hide-users=false
logind-check-graphical=true

[Seat:*]
user-session=shadow
greeter-session=lightdm-gtk-greeter
session-wrapper=lightdm-xsession
autologin-user-timeouts=0
